name: API Health Smoke Test
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    health-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install dependencies
              run: pnpm install
            - name: Build API
              run: pnpm build
            - name: Start API
              run: |
                  nohup pnpm start &
                  sleep 5
            - name: Smoke test /health
              run: |
                  curl -sf http://localhost:4000/health || exit 1
            - name: Integration test /api/v1/events
              run: |
                  curl -sf http://localhost:4000/api/v1/events || exit 1
